# Only used for development.

version: '3'
services:
  setup:
    build: .
    depends_on:
      - postgres
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=beyondludus_development
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    command: "bin/rails db:migrate"
  postgres:
    # 9.6 is freshest version available in Google Cloud SQL
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beyondludus_development
      - PGDATA=/var/lib/postgresql/data
  db_data:
    image: postgres:9.6-alpine
    volumes:
      - /var/lib/postgresql/data
    command: "/bin/true"
  sidekiq:
    build: .
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=beyondludus_development
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - redis
    command: "bin/bundle exec sidekiq -C config/sidekiq.yml"
  redis:
    image: redis:4.0.10-alpine
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=beyondludus_development
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    command: "bin/bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/beyondludus
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - setup
