steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      docker pull us.gcr.io/<%= fetch_env_var("PROJECT_ID") %>/<%= fetch_env_var("REPO_NAME") %>:latest || true
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'us.gcr.io/<%= fetch_env_var("PROJECT_ID") %>/<%= fetch_env_var("REPO_NAME") %>:latest', '-t', 'us.gcr.io/<%= fetch_env_var("PROJECT_ID") %>/<%= fetch_env_var("REPO_NAME") %>:latest', '-t', 'us.gcr.io/<%= fetch_env_var("PROJECT_ID") %>/<%= fetch_env_var("REPO_NAME") %>:<%= fetch_env_var("COMMIT_SHA") %>', '.' ]
images:
- 'us.gcr.io/<%= fetch_env_var("PROJECT_ID") %>/<%= fetch_env_var("REPO_NAME") %>:latest'
- 'us.gcr.io/<%= fetch_env_var("PROJECT_ID") %>/<%= fetch_env_var("REPO_NAME") %>:<%= fetch_env_var("COMMIT_SHA") %>'
timeout: 3600s
