default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: postgres
  port: 5432

development:
  <<: *default
  database: beyondludus_development

test:
  <<: *default
  database: beyondludus_test

production:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  database: beyondludus_production
