default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: postgres
  port: 5432

development:
  <<: *default
  database: beyondludus_development

test:
  <<: *default
  database: beyondludus_test

production:
  <<: *default
  database: beyondludus_production
  username: beyondludus
  password: <%= ENV['BEYONDLUDUS_DATABASE_PASSWORD'] %>
