apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  # Adding new entries here will make them appear as files in the deployment.
  nginx.conf: |
    user  nginx;
    worker_processes auto;
    pid /var/run/nginx.pid;
    daemon off;

    error_log /dev/stderr warn;

    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /dev/stdout  main;
        rewrite_log on;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout  65;

        # brotli on;
        gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
